server {
    listen ${PORT};
    server_name _;
    client_max_body_size 20M;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA — ทุก route ชี้ไป index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
