# Generated by Django 4.2.13 on 2026-06-09 10:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสพนักงาน')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('staff', 'พนักงาน'), ('depthead', 'หัวหน้าแผนก'), ('deptrep', 'ตัวแทนแผนก'), ('checker', 'ผู้ตรวจสอบ'), ('executive', 'ผู้บริหาร')], default='staff', max_length=20, verbose_name='บทบาท')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมลสำหรับแจ้งเตือน')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแผนก')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสแผนก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แผนก',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ot_hours_weekday', models.DecimalField(decimal_places=1, default=4.0, max_digits=4, verbose_name='ชม. OT สูงสุดวันธรรมดา')),
                ('max_ot_hours_holiday', models.DecimalField(decimal_places=1, default=7.0, max_digits=4, verbose_name='ชม. OT สูงสุดวันหยุด')),
                ('rate_multiplier_weekday', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='อัตราคูณวันธรรมดา')),
                ('rate_multiplier_holiday', models.DecimalField(decimal_places=2, default=3.0, max_digits=4, verbose_name='อัตราคูณวันหยุด')),
                ('notify_on_submit', models.BooleanField(default=True, verbose_name='แจ้งเตือนเมื่อยื่นคำร้อง')),
                ('notify_on_approve', models.BooleanField(default=True, verbose_name='แจ้งเตือนเมื่ออนุมัติ')),
                ('notify_on_reject', models.BooleanField(default=True, verbose_name='แจ้งเตือนเมื่อตีกลับ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ตั้งค่าระบบ',
            },
        ),
        migrations.CreateModel(
            name='OTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='วันที่ทำงาน OT')),
                ('day_type', models.CharField(choices=[('weekday', 'วันธรรมดา'), ('holiday', 'วันหยุด')], max_length=10, verbose_name='ประเภทวัน')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('ot_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='จำนวนชั่วโมง OT')),
                ('work_detail', models.TextField(verbose_name='รายละเอียดงาน')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='สถานที่')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าตอบแทน (บาท)')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('submitted', 'ยื่นแล้ว'), ('head_approved', 'หัวหน้าอนุมัติ'), ('head_rejected', 'หัวหน้าตีกลับ'), ('rep_forwarded', 'ตัวแทนส่งต่อแล้ว'), ('checker_approved', 'ผู้ตรวจสอบอนุมัติ'), ('checker_rejected', 'ผู้ตรวจสอบตีกลับ'), ('completed', 'เสร็จสิ้น')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('head_approved_at', models.DateTimeField(blank=True, null=True)),
                ('head_note', models.TextField(blank=True, verbose_name='หมายเหตุหัวหน้า')),
                ('rep_forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('checker_approved_at', models.DateTimeField(blank=True, null=True)),
                ('checker_note', models.TextField(blank=True, verbose_name='หมายเหตุผู้ตรวจสอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checker_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_approvals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='แผนก')),
                ('head_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_approvals', to=settings.AUTH_USER_MODEL)),
                ('rep_forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_forwards', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_requests', to=settings.AUTH_USER_MODEL, verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'คำร้อง OT',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('partial', 'สำเร็จบางส่วน')], max_length=10)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติการนำเข้า',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อวันหยุด')),
                ('holiday_type', models.CharField(choices=[('official', 'วันหยุดราชการ'), ('compensation', 'วันหยุดชดเชย'), ('special', 'วันหยุดพิเศษ')], default='official', max_length=20, verbose_name='ประเภท')),
                ('year', models.IntegerField(verbose_name='ปี พ.ศ.')),
                ('is_system', models.BooleanField(default=False, verbose_name='ระบบสร้างให้อัตโนมัติ')),
            ],
            options={
                'verbose_name': 'วันหยุด',
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='การกระทำ')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.department', verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='วันที่')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='เวลาเข้า')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='เวลาออก')),
                ('source_file', models.CharField(blank=True, max_length=200, verbose_name='ไฟล์ต้นทาง')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลเวลา',
                'ordering': ['-log_date'],
                'unique_together': {('user', 'log_date')},
            },
        ),
    ]
