# Generated by Django 4.2.13 on 2026-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemsettings_tu_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='สิทธิ์เพิ่มเติม'),
        ),
    ]
