# Generated by Django 4.2.13 on 2026-06-11 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_extra_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_month', models.CharField(max_length=7, unique=True, verbose_name='เดือน (พ.ศ.)')),
                ('deadline_date', models.DateField(verbose_name='วันปิดรับ')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_deadlines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'กำหนดวันปิดรับ OT',
                'ordering': ['-thai_month'],
            },
        ),
    ]
