# Generated by Django 4.2.13 on 2026-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_ot_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrequest',
            name='rep_note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุตัวแทนแผนก'),
        ),
    ]
