# Generated by Django 4.2.13 on 2026-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_ot_deadline_and_rep_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='attendance_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='สถานะเข้างาน'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='time_period',
            field=models.CharField(blank=True, choices=[('เช้า', 'เช้า'), ('ปกติ', 'ปกติ')], max_length=10, verbose_name='กะการทำงาน'),
        ),
    ]
