# Generated by Django 4.2.13 on 2026-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_ot_deadline_and_rep_note'),
    ]

    # หมายเหตุ: เดิมมี AddField ซ้ำกับ 0009_add_time_period_attendance_status_to_timelog
    # (เกิดจาก merge conflict เก่า) — เอา operations ออกเพื่อไม่ให้ชนกันตอนสร้างฐานข้อมูลใหม่
    # ฐานข้อมูลเดิม (sqlite dev) มี migration นี้ถูก mark ว่า applied ไปแล้วจึงไม่กระทบ
    operations = []
