# Generated by Django 4.2.13 on 2026-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_ot_budget_to_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'มาทำงาน'), ('absent', 'ขาดงาน'), ('leave', 'ลา'), ('holiday', 'วันหยุด')], default='normal', max_length=10, verbose_name='สถานะการมา'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'แอดมิน'), ('staff', 'พนักงาน'), ('depthead', 'หัวหน้างาน'), ('deptrep', 'ตัวแทนฝ่าย'), ('checker', 'ผู้ตรวจสอบ'), ('executive', 'ผู้บริหาร')], default='staff', max_length=20, verbose_name='บทบาท'),
        ),
    ]
