# Generated by Django 4.2.13 on 2026-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_timelog_time_period'),
        ('api', '0010_add_ot_budget_to_department'),
    ]

    operations = [
    ]
