# Generated by Django 4.2.13 on 2026-06-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260614_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'แอดมิน'), ('staff', 'พนักงาน'), ('depthead', 'หัวหน้างาน'), ('deptrep', 'ตัวแทนฝ่าย'), ('checker', 'ผู้ตรวจสอบ'), ('executive', 'ผู้บริหาร')], default='staff', max_length=20, verbose_name='บทบาท'),
        ),
    ]
