# Generated by Django 4.2.13 on 2026-06-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_timelog_attendance_status_alter_user_role'),
        ('api', '0012_alter_user_role'),
    ]

    operations = [
    ]
