# Generated by Django 4.2.13 on 2026-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20260618_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='attendance_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='สถานะเข้างาน'),
        ),
    ]
