# Generated by Django 5.2.15 on 2026-06-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_timelog_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ot_submitted', 'ยื่นคำร้อง OT ใหม่'), ('ot_head_approved', 'หัวหน้าอนุมัติ'), ('ot_head_rejected', 'หัวหน้าตีกลับ'), ('ot_rep_forwarded', 'ตัวแทนส่งต่อแล้ว'), ('ot_checker_approved', 'ผู้ตรวจสอบอนุมัติ'), ('ot_checker_rejected', 'ผู้ตรวจสอบตีกลับ'), ('no_ot_declared', 'แจ้งไม่มีโอทีประจำเดือน')], max_length=30),
        ),
        migrations.CreateModel(
            name='NoOTDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greg_year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_ot_declarations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_ot_declarations', to='api.department')),
            ],
            options={
                'ordering': ['-greg_year', '-month'],
                'unique_together': {('department', 'greg_year', 'month')},
            },
        ),
    ]
