# Generated by Django 4.2.13 on 2026-06-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_notification_is_read_and_more'),
        ('api', '0016_user_profile_image'),
    ]

    operations = [
    ]
