# Generated by Django 4.2.13 on 2026-06-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260628_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ot_submitted', 'ยื่นคำร้อง OT ใหม่'), ('ot_head_approved', 'หัวหน้าอนุมัติ'), ('ot_head_rejected', 'หัวหน้าตีกลับ'), ('ot_rep_forwarded', 'ตัวแทนส่งต่อแล้ว'), ('ot_checker_approved', 'ผู้ตรวจสอบอนุมัติ'), ('ot_checker_rejected', 'ผู้ตรวจสอบตีกลับ'), ('no_ot_declared', 'แจ้งไม่มีโอทีประจำเดือน'), ('budget_set', 'ผู้ตรวจสอบตั้งงบประมาณ OT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='attendance_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='สถานะเข้างาน'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, default='', verbose_name='รูปโปรไฟล์ (base64)'),
        ),
        migrations.CreateModel(
            name='DepartmentMonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='ปี (Gregorian)')),
                ('month', models.PositiveSmallIntegerField(verbose_name='เดือน (1-12)')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='งบประมาณ OT (บาท)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='api.department')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'งบประมาณ OT รายเดือน',
                'ordering': ['-year', '-month'],
                'unique_together': {('department', 'year', 'month')},
            },
        ),
    ]
