# Generated by Django 4.2.13 on 2026-06-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_department_monthly_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อกะ')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่มงาน')),
                ('end_time', models.TimeField(verbose_name='เวลาเลิกงาน')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='เวลาผ่อนผันสาย (นาที)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'กะการทำงาน',
                'verbose_name_plural': 'กะการทำงาน',
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterField(
            model_name='timelog',
            name='time_period',
            field=models.CharField(blank=True, choices=[('เช้า', 'เช้า'), ('ปกติ', 'ปกติ')], max_length=10, verbose_name='กะการทำงาน (ข้อความเดิม)'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='api.shift', verbose_name='กะการทำงาน'),
        ),
    ]
