# Generated by Django 4.2.13 on 2026-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_department_monthly_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ot_submitted', 'ยื่นคำร้อง OT ใหม่'), ('ot_head_approved', 'หัวหน้าอนุมัติ'), ('ot_head_rejected', 'หัวหน้าตีกลับ'), ('ot_rep_action_needed', 'ตัวแทนฝ่ายต้องดำเนินการ'), ('ot_rep_forwarded', 'ตัวแทนส่งต่อแล้ว'), ('ot_checker_approved', 'ผู้ตรวจสอบอนุมัติ'), ('ot_checker_rejected', 'ผู้ตรวจสอบตีกลับ'), ('no_ot_declared', 'แจ้งไม่มีโอทีประจำเดือน'), ('budget_set', 'ผู้ตรวจสอบตั้งงบประมาณ OT')], max_length=30),
        ),
    ]
