# Generated by Django 4.2.13 on 2026-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_ot_rep_action_needed_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrequest',
            name='rep_document',
            field=models.FileField(blank=True, null=True, upload_to='ot_documents/', verbose_name='เอกสาร Excel ที่แนบ'),
        ),
    ]
