# Generated by Django 4.2.13 on 2026-06-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shift_alter_timelog_time_period_timelog_shift'),
        ('api', '0020_add_rep_document_field'),
    ]

    operations = [
    ]
