# Generated by Django 4.2.13 on 2026-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260630_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='tu_api_enabled',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้ TU API'),
        ),
    ]
