# Generated by Django 4.2.13 on 2026-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_systemsettings_tu_api_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrequest',
            name='rep_document_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='เนื้อหาไฟล์เอกสาร (เก็บใน DB)'),
        ),
        migrations.AddField(
            model_name='otrequest',
            name='rep_document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อไฟล์เอกสาร'),
        ),
    ]
