# Generated by Django 4.2.13 on 2026-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_otrequest_rep_document_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Log'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'แผนก', 'verbose_name_plural': 'แผนก'},
        ),
        migrations.AlterModelOptions(
            name='departmentmonthlybudget',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'งบประมาณ OT รายเดือน', 'verbose_name_plural': 'งบประมาณ OT รายเดือน'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'วันหยุด', 'verbose_name_plural': 'วันหยุด'},
        ),
        migrations.AlterModelOptions(
            name='importhistory',
            options={'ordering': ['-imported_at'], 'verbose_name': 'ประวัติการนำเข้า', 'verbose_name_plural': 'ประวัติการนำเข้า'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'การแจ้งเตือน', 'verbose_name_plural': 'การแจ้งเตือน'},
        ),
        migrations.AlterModelOptions(
            name='otdeadline',
            options={'ordering': ['-thai_month'], 'verbose_name': 'กำหนดวันปิดรับ OT', 'verbose_name_plural': 'กำหนดวันปิดรับ OT'},
        ),
        migrations.AlterModelOptions(
            name='otrequest',
            options={'ordering': ['-work_date'], 'verbose_name': 'คำร้อง OT', 'verbose_name_plural': 'คำร้อง OT'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'ตั้งค่าระบบ', 'verbose_name_plural': 'ตั้งค่าระบบ'},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-log_date'], 'verbose_name': 'ข้อมูลเวลา', 'verbose_name_plural': 'ข้อมูลเวลา'},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ot_rate_holiday',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=6, verbose_name='อัตราค่าจ้าง OT วันหยุด (บาท/ชม.)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ot_rate_weekday',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=6, verbose_name='อัตราค่าจ้าง OT วันธรรมดา (บาท/ชม.)'),
        ),
    ]
