# Generated by Django 4.2.13 on 2026-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_auditlog_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='ot_hours_override',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='จำนวน OT ที่แอดมินกำหนด'),
        ),
    ]
